# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


class_list =  [

["Introduction to Entrepreneurship", "ESBM 3100", "Introduces non-business students to the multiple facets of entrepreneurship and the entrepreneurial process. Entrepreneurship is a process of fundamental transformation: from innovative idea to enterprise and from enterprise to valuethus, entrepreneurship is more than a business practice. Innovation is central to this process and students will be challenged to develop creative solutions to a problem or need. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["Principles of Business for Entrepreneurs", "ESBM 3200", "Provides non-business students with a basic understanding of the business principles required to start and grow an entrepreneurial venture. It is intended for individuals who have not taken a marketing, accounting or finance course. This course will focus on two aspects of business that are critical to the success of any new venture: marketing and financial management. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["Writing a Venture Plan", "ESBM 4100", "Requires non-business students to engage in a rigorous, thoughtful and challenging process essential to planning a new venture. Using their own concept, students will develop a strategy to start and grow a venture. Communicating the plan is an essential element of this course and students will learn when and how to write a plan and make effective presentations. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Business"],
["Introduction to Entrepreneurship for Engineers", "ESBM 3100-3", "Introduces non-business students to the multiple facets of entrepreneurship and the entrepreneurial process. Entrepreneurship is a process of fundamental transformation: from innovative idea to enterprise and from enterprise to valuethus, entrepreneurship is more than a business practice. Innovation is central to this process and students will be challenged to develop creative solutions to a problem or need. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["The Entrepreneurial Artist", "MUSC 4988/5988", "Learn the core principles of entrepreneurship, such as idea formation, venture models, opportunity assessment, market analysis, and strategies for launching a venture, and apply them to their own entrepreneurial ideas. Lectures, projects, entrepreneur interviews, and case studies will culminate in a feasibility study for an original entrepreneurial concept. Recommended prereq., MUSC 4918. Same as MUSC 5988.", "Music"],
["Building Your Music Career", "MUSC 2918/5918", "Students acquire the practical skills they need to build their career as professional musicians, as well as explore the many options for putting their music education to work in the marketplace. Students will also explore the state of live music-making today and explore ways to maintain relevance for themselves and their art in an ever-changing world. Formerly MUSC 4918. Restricted to College of Music majors only. Prerequisites: Restricted to College of Music undergraduate students only.", "Music"],
["Startup Essentials for Software Entrepreneurship", "CSCI 4830/7000", "Students learn about agile methodologies in software development in regard to entrepreneurship", "Engineering"],
["Business Methods and Economics for Engineers", "EMEN 4100", "Covers cost concepts, financial statements, and the company economic environment. Includes concepts and methods of analysis of the time value of money, comparison of project alternatives before and after taxes, cash flows, replacement analysis, risk management, and financial cash statements. Restricted to junior or senior in the College of Engineering and Applied Science. Prerequisites: Restricted to students with 57-180 credits (Junior or Senior) College of Engineering students only.", "Engineering"],
["Tech and Entrepreneurship in the Developing World", "EMEN 4830", "", "Engineering"],
["Technology Ventures and Marketing", "EMEN 5090", "Acquiring marketing know-how is essential for engineers interested in technology and product development. Students learn the basic tenets of marketing with emphasis on developing a technology innovation into a commercially successful product. Special attention given to customer development as a key aspect of product development. Course designed to be of interest to engineers in existing companies and startups. Highlighted will be in-depth discussions of real-world case studies and providing the student with marketing strategies for the high tech environment. Non-EMP students require instructor permission. Restricted to graduate students in Engineering Management Program (EMEN) only. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only."],
["Entrepreneurial Business Plan Preparation", "EMEN 5825", "Instructs students in the necessary elements of a business plan and how to prepare a complete, well-written plan for an entrepreneurial business venture. Students work in teams to create a business concept and take it through business plan completion. Recommended prereq., EMEN 5020 or equivalent. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Lean and Agile Management", "EMEN 5500", "Operations Management has evolved and broadened from a sole focus on the manufacturing of hardware to a more universal set of concepts, management methods, and practical tools spanning manufacturing, supply chains, product development, software development, project management, support services, and accounting. This new approach can best be described as lean and agile management. Credit not granted for this course and OPIM 6080. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Entrepreneurial Business Plan Preparation", "EMEN 5825", "Instructs students in the necessary elements of a business plan and how to prepare a complete, well-written plan for an entrepreneurial business venture. Students work in teams to create a business concept and take it through business plan completion. Recommended prereq., EMEN 5020 or equivalent. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Entrepreneurial Innovation and Public Policy", "LAWS 5201", "Explores cutting edge questions around entrepreneurship, including being an entrepreneur, leadership and what makes a great founding team, building and scaling a business, entrepreneurial communities, financing entrepreneurial companies, leadership in government, entrepreneurship and innovation policy. Restricted to Law students only. Prerequisites: Restricted to Law students only.", "Law"],
["Philosophy of Entrepreneurship", "LAWS 6271", "", "Law"],
["Venture Capital and Private Equity", "LAWS 7271", "Provides overview of the legal and financial principles to represent privately held companies, their founders and managers, and their investors. Emphasizes transaction structuring rather than judicial opinions. Includes the organization and financing of start-ups, structuring buyout transactions, exit strategies, legal organization of investment funds and other financial intermediaries. Discusses the relevant regulatory landscape, including securities law, bankruptcy, ERISA, and tax law.", "Law"],
["Entrepreneurial Law Clinic", "LAWS 7619", "Advise indigent clients who need legal services in the founding of their business or not-for-profit firms, registering LLCs, and drafting employment and intellectual property agreements. Prereq., two of the following courses: Agency Partnership and the LLC, Corporations, Securities, Seminar on Corporate Law, Law and Finance for Entrepreneurs, Accounting Issues for Lawyers, Patent Law, Trademark, and International Business Transactions. Prerequisites: Restricted to Law students only.", "Law"],
["Principles of Business for Entrepreneurs", "ESBM 3200", "Provides non-business students with a basic understanding of the business principles required to start and grow an entrepreneurial venture. It is intended for individuals who have not taken a marketing, accounting or finance course. This course will focus on two aspects of business that are critical to the success of any new venture: marketing and financial management. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Business"],
["Entrepreneurial Environments", "ESBM 3700", "Introduces entrepreneurship. Addresses opportunity recognition, target markets, industry analysis, business model identification, sources of funding, managing rapid growth, and writing feasibility studies. Examines alternative forms of entrepreneurship such as franchising, corporate entrepreneurship, family business, and social entrepreneurship. Prereqs., BCOR 2000, 2050, 2100, 2150, or BCOR 2000, 2200, 2300, 2400. Restricted to students with 52 hours completed. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Entrepreneurial Finance", "ESBM 4570", "Focuses on the financial concepts, issues, methods, and industry practices relevant to entrepreneurial decision makers. Addresses a variety of topics including financial valuation, various sources of funds, structures and legal issues in arranging financing, the private and public venture capital markets, and preparation for, and execution of, an initial public securities offering. Provides an understanding of the segments of the capital markets specializing in start-ups and growth financing. Prereq., BCOR 2200. Restricted to Business majors with 52-180 units completed. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Business Plan Preparation", "ESBM 4830", "Work as part of a small team, with the focus on the process of creating a plan from the business concept and model through all of the elements of a professionally written business plan document. Prereqs., ESBM 3700 and 4570. Same as EMEN 4825. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Entrepreneurship", "MBAX 6100", "Examines the environments of entrepreneurial firms from start-up to development of ventures. Allows students to assess their fit with entrepreneurial firms. Key element is learning the process of determining the difference between ideas and commercializable opportunities through feasibility analysis and plans. Prereq., MBAC 6020 or instructor consent. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Entrepreneurial Finance", "MBAX 6110", "Addresses a variety of topics including financial valuation, various sources of funds, structures and legal issues in arranging financing, the private and public venture capital markets, and preparation for, and execution of, an initial public securities offering. Prereq., MBAC 6020. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Business Plan Preparation", "MBAX 6170", "Completion of a sophisticated business plan within task groups from concept through all the elements of a professionally written business plan. Provides students high interaction with businesses and entrepreneurs. Prereq., MBAC 6020 and MBAX 6100, or instructor consent. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Start Up Execution", "MBAX 6180", "Covers a variety of topics in applied entrepreneurship, including the steps required to legally launch a business and procedures for executing standard business functions (organization, marketing, sales, advertising, operations, team building, and finance) with minimal resources (cash, personnel, and equipment). Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Projects in Entrepreneurial Companies", "MBAX 6190", "Limited to 12 students per section, each student is matched with an entrepreneurial company to complete a project that is key to company strategy. Students experience total company environment from the top management level through attending management meetings and interacting with cross-functional managers and employees. E-mail and face-to-face meetings result in discussing opportunities and issues resulting from experiences in companies. Prereq., MBAX 6100. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["New Product Development", "MBAX 6360", "Provides a better understanding of the new-product development process, highlighting the inherent risks and strategies for overcoming them. Using a combination of lectures, cases, and a project, this course examines the process of designing, testing, and launching new products. Emphasizes the interplay between creativity and analytical marketing research throughout the development process. Also covers branding issues, such as brand extensions and their impact on brand equity. Prereq., MBAC 6090. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Environmental Entrepreneurship", "MBAX 6130", "", "Business"],
["Entrepreneurship and the Venture Capital Process", "MBAX 6805", "This course will be articulated into two main parts, tightly interrelated: Entrepreneurship and the Venture Capital Process. The first part has the objective to lead the students to understand what venture capital is, how it works, how you structure capital raising, and how it helps entrepreneurial initiatives. The second part concerns how venture capitalists manage their operations, secure investment deals, and maintain their portfolios. Prereqs., MBAC 6011, 6020, 6031, 6040, 6060, 6080, and 6090. Restricted to LAWS students and graduate students in business. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Social Entrepreneurship for Emerging Markets", "MBAX 6845", "Social entrepreneurs adopt business approaches to solving global, social and environmental problems that have not been effectively addressed by government, business or traditional nonprofits. The course provides a framework for student teams to assist social entrepreneurs in developing countries, helping them achieve their social mission while operating sustainably and with measurable impact. Prereqs., MBAC 6010, 6060, and 6090. Recommended prereq., MBAX 6170. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Mobile App Development", "ATLS 4519", "Analyzes special interest areas of multidisciplinary technology, arts and media research and practice. May be repeated up to 9 total credit hours. Prereq., instructor consent. Recommended prereqs., ATLS 2000, ATLS 3010, and ATLS 3020. Same as ATLS 3519, 5519 and 6519.", "Engineering"],






]

student_groups = [

["Active Entrepreneurs","CU Student Entrepreneurship Collaboration.","active.png","https://www.aecuboulder.com"],

["Boulder Beta Alpha Psi","Leeds Business Fraternity.","BAP.png","http://leeds.colorado.edu/club/betaalphapsi"],

["Boulder Creatives","Cross-campus student club/nonprofit organization performing high-level design, marketing, and advertising work for Colorado companies.","Lcreatives.png","http://bouldercreatives.com"],

["Business Law Association (BLA)","Provides law students with contacts and info about the business world.","No Photo URL","https://www.colorado.edu/law/students/organizations"],

["Collegiate Social Impact Initiatives (CSII)","We are college students working as effective and sustainable agents of positive social impact.","CSII.png","http://csii.colorado.edu"],

["CU Biotech Club","Student organization for business, engineering, and life sciences students interested in biotechnology.","Biotech.png","http://www.cubiotechclub.com/"],

["CU CEO","Undergraduate entrepreneurship club for Leeds School of Business students.","CEO.png","http://leeds.colorado.edu/club/ceo"],

["CU Energy Club","Interdisciplinary entrepreneurship club for students interested in the energy industry.","energy.png","http://cuenergy.org"],

["CU New Venture Challenge (NVC)","Interdisciplinary cross-campus business competition.","nvc.png","http://cunvc.org"],

["CUSkills","Connecting students to peers who can help.","cuskills.png","http://cuskills.com"],

["CU Women In Business Club","Leeds focused, student club for females in business.","No Photo URL","https://leeds.colorado.edu/club/mbawomeninbusiness"],

["Entrepreneurial Solutions","Leeds focused student consulting organization.","EntSolutions.png","http://leeds.colorado.edu/club/entrepsolutions"],

["InnovateCU","Software Development and Computer Science Club.","innovateCU.png","http://innovatecu.com"],

["Leeds Entrepreneurship Alliance (LEA)","MBA student club, Leeds focused.","LEA.png","https://cuboulderlea.wordpress.com/"],

["The Silicon Flatirons Student Group","Interdisciplinary research center for Law Students and ITP focusing on entrepreneurship.","silicon.png","http://silicon-flatirons.org/"],

["StartUp CU","Cross-campus entrepreneurship club for new startups.","Startupcu.png","http://startupcu.com"],

["TEDxCU","CU’s own TEDx.","TED.png","http://tedxcu.com"],




]

funding = [

["Access Venture Partners","Access Venture Partners is an early stage venture capital fund. Together over the past 14 years, the partners at Access Venture Partners have invested in over fifty early stage companies and have served as founders and early executives of numerous companies. Through this experience we have built an understanding of how to navigate the challenges associated with building successful companies and drive them to success.","http://www.boulderstartups.org/wp-content/uploads/2011/04/access-206x300.gif","http://www.accessvp.com/index.php", "VC"],

["Altira","Altira is committed to building companies that will transform the energy sector. Founded in 1996 with the sole purpose of successfully investing in the energy technology sector, Altira Group focuses on growth technology companies spanning the energy value chain from source to resource, and takes an active lead investment role by providing solid follow-on capabilities.","http://www.boulderstartups.org/wp-content/uploads/2011/04/altira_nav2_r1_c2.gif","http://www.altiragroup.com/index.html", "VC"],

["Boulder Ventures","Our investment approach has remained consistent for more than fifteen years: We invest in early stage information technology and life science companies in Colorado and the Mid-Atlantic region. We invest in serial entrepreneurs with the proven ability to create and lead successful teams. We partner with leading venture capital funds to form investor syndicates that bring experience as well as capital to market-leading companies.","http://www.highway12ventures.com/wp-content/uploads/2011/10/Boulder_ventures-logo-AC128D79E5-seeklogo.com_.gif","http://www.boulderventures.com/", "VC"],

["Point B Capital","Point B Capital is more than an investor.  Their relationship with Point B gives them unique insight into winning companies—with over 15 years of helping them grow and thrive. They make equity investments and manage complex deals that capture value and leverage the rich relationships that Point B has developed since 1995. Their network includes more than 300 clients across 27 industries. They build value for both portfolio companies and Point B’s broader client base by bringing the two together for mutual benefit.","http://www.boulderstartups.org/wp-content/uploads/2011/04/point-b-capital-logo02.png","http://www.pointbcap.com/index.html", "VC"],

["eonCapital Ventures","eonCapital Ventures invest in seed and early-stage Software as a Service (SaaS) and mobile application businesses. Like the creative entrepreneur, we saw a problem and desired a solution. Our goal is to help fill the funding gap for entrepreneurs of seed and early-stage companies. As entrepreneurs, we understood what it takes to build a company from the ground up and the challenges presented from concept through development and into the growth phase.","http://www.boulderstartups.org/wp-content/uploads/2011/04/eon-logo.png","http://www.eonbusiness.com/", "VC"],

["Flywheel Ventures","Flywheel Ventures focuses on seed-stage and early-stage companies with solutions that address key global challenges in digital services, infrastructure technology, energy technology, and water technology. Flywheel works with each entrepreneur to grow their company in a capital-efficient manner by focusing on a 'beachhead' market, often overseas, leveraging the firm’s formal Global Advisor network and informal network of worldwide experts.","http://www.boulderstartups.org/wp-content/uploads/2011/04/flywheel.gif","http://www.flywheelventures.com/index.php", "VC"],

["Foundry Group","The Foundry Group is Boulder’s most well-known venture capitalism firm, focused on making investments in early-stage information technology, Internet and software startups with a portfolio that includes companies like Zynga, Trada, SendGrid, and many more. Foundry’s current venture fund of $225m was launched in October 2010 and is managed by four managing directors who collectively have over five decades of experience in venture capital investing and over three decades of entrepreneurial experience in founding and working in senior operating roles inside technology startups.","http://www.boulderstartups.org/wp-content/uploads/2011/04/FoundryGroup.jpg","http://foundrygroup.com/", "VC"],

["Grotech Ventures","As one of the longest-established firms in the venture industry, Grotech Ventures has built a reputation for being a collaborative, long-term partner for CEOs and entrepreneurs by aligning our definition of success with that of our partners. Grotech Ventures initially invests from $500,000 to $5 million and looks to continue investing and building value throughout the growth of your enterprise. Grotech’s portfolio includes local companies such as Collective Intellect and Giveo.","http://www.boulderstartups.org/wp-content/uploads/2011/04/grotech.jpg","http://www.grotech.com/index.php", "VC"],

["High Country Venture","High Country Venture makes active investments in promising early-stage companies that have scalable, innovative technology. We tend to take an active role in our investments, and frequently work with the founding team to foster growth, transform markets and create long-term value.","http://www.boulderstartups.org/wp-content/uploads/2011/04/logo.png","http://highcountryventure.com/newsite/wordpress/", "VC"],

["Highway 12","Like the original venture firms of the 70′s and 80′s, Highway 12 is not sector focused. The firm’s founding investment thesis is that the  Intermountain West  (the fastest growing region in the country) will produce a disproportionate amount of highly successful companies over the next couple of decades. With a singular focus on providing the early rounds of investment in the most promising high-growth companies in the region, the firm does not invest all over the country or in sectors that go in and out of favor. This unique focus on the region sets Highway 12 apart from other venture capital firms employing the latest strategy du jour. The firm spends all their time and energy here in the West, making them better able to help you gather the resources you need.","http://www.boulderstartups.org/wp-content/uploads/2011/04/highway12.jpg","http://www.highway12ventures.com/", "VC"],

["Infield Capital","Infield Capital is committed to fueling the early-stage companies that are driving change in the transportation industry.  We have an emphasis on technologies aimed at rethinking the powertrain – those things between the 'key and the wheel' that will reduce our reliance on oil and our emissions of greenhouse gases.  We have a strong belief in the entrepreneur that stems from years in manufacturing and high-tech operating roles, and an investment model that uniquely couples financial capital with human capital.","http://www.boulderstartups.org/wp-content/uploads/2010/12/Infield.png","http://www.infieldcapital.com/", "VC"],

["ACCION New Mexico-Arizona-Colorado","ACCION New Mexico • Arizona • Colorado is an award-winning nonprofit organization that invests in the community’s most important asset – human potential. By increase access to business credit, making loans and providing training to help emerging and existing entrepreneurs realize their dreams, ACCION empowers people to be catalysts for positive change – one small business at a time.","http://coloradomicrofinance.org/wp-content/uploads/2011/05/ACCION-NM-AZ-CO.jpg","http://www.accionnm.org/", "MFG"],

["Colorado Enterprise Fund","The Colorado Enterprise Fund was founded in 1976 as a non-profit lending source specializing in loans up to $250,000 to support small business. Many small businesses that are not able to receive traditional bank financing can get support through CEF. By offering loans, guidance, training, and resources to small and emerging businesses, CEF is an important conduit to local community vitality and economic development in Colorado.","http://www.coloradoenterprisefund.org/templates/cef/i/pageHeaders/home_header.jpg","http://www.coloradoenterprisefund.org/", "MFG"],

["Colorado PERA Mile High Fund","Colorado PERA Mile High Fund was launched in October of 2012 to invest a portion of it’s $40 billion fund in Colorado businesses that have a nexus in Colorado and currently have the support of a financial sponsor. The PERA Mile High Fund is intended to be a pool of growth capital for Colorado businesses.","http://innovationews.com/blog/wp-content/uploads/2012/10/colorado-pera-featured1.jpg","http://www.copera.org/pera/about/latestnews.htm#ColoradoFund", "MFG"],

["Rocky Mountain MicroFinance Institute (RMMFI)","The Rocky Mountain MicroFinance Institute (RMMFI) is a non-profit organization that provides learning, lending, and coaching to grow Community Entrepreneurs who build businesses to advance along the pathway to self-sufficiency and self-worth. RMMFI’s brand of microfinance combines affordable and approachable business support services and flexible microloans to help individuals turn a good idea into an income-generating business.","http://www.boulderstartups.org/wp-content/uploads/2011/04/rmmfi.jpg","http://www.rmmfi.org/", "MFG"],

["CU Deming Center Venture Fund","The Deming Center Venture Fund provides both capital and resource support for emerging companies in Boulder and surrounding communities. The DCVF focuses on early stage investments, providing financial support that early-stage companies often require to develop and test new products and technologies.","http://cudcvf.org/wp-content/uploads/2012/08/image_1_main.png","cudcvf.org", "AMS"],

["Fraser McCombs Capital","Fraser McCombs Capital is a venture firm focused on early-stage technology companies within the automotive space. We are the first and only venture fund that’s managed by automotive entrepreneurs and dealers. We have long standing relationships with Tier 1, 2, and 3 vendors, and connections with leading OEM executives and principals of the largest dealer groups. This allows us to provide key introductions for our portfolio companies.","http://mccombspartners.com/wp-content/uploads/2011/12/FMC_500x182.jpg","fmcap.com", "AMS"],

["Galvanize","Physical proximity to other doers, makers and innovators is important. There is no manual for entrepreneurial success. It’s a journey. A journey that is only limited on your ability to learn and grow. This type of learning comes from doing—from experience. The skills, connections, and mentorship your journey requires are coalesced here.","http://startupphenomenon.com/2013/wp-content/uploads/2013/06/galvanize-2.jpeg","galvanize.it", "AMS"],

["The Impact Angel Group","The Impact Angel Group is a network of angel investors equally dedicated to making a difference and realizing a return. The group applies best-of-breed practices to social impact investing and connects viable social entrepreneurs with financial, intellectual and human capital. The mission is to create social impact success stories for both entrepreneurs and investors. The group is a source of capital that exists to support the existing ecosystem and connect entrepreneurs and investors to the resources they need to succeed.","http://50.87.144.189/~tiag/wp-content/uploads/2013/07/cropped-cropped-istock_000018764690large1.jpg","http://impactangelgroup.com/", "AMS"],

["John Ives Tahoma Fund","John has been an early-stage investor and entrepreneur since 1997. He is co-founder of Chips on the Deck, a networking organization for Colorado-based semiconductor, EDA and embedded system entrepreneurs. He is also the founder of Boulder Angels, which organizes the activities of active, professional angel investors in Boulder County.","http://www.johnives.com/wp-content/uploads/2013/06/iveslogo3.png","http://www.johnives.com/", "AMS"],

["Open Angel Forum (OAF)","The Open Angel Forum (OAF) is dedicated to providing entrepreneurs with access to the angel investor community based solely on merit (and without fees). Additionally, we strive to build collaboration between angel investors and to inspire high-net worth individuals to become angels. Leading the Boulder chapter are none other than Brad Feld and David Cohen.","http://www.boulderstartups.org/wp-content/uploads/2011/04/openangelforum.jpg", 'N/A', "AMS"],

["Rockies Venture Club","For over 28 years, Colorado has looked to the Rockies Venture Club to connect investors, service providers, and entrepreneurs. Rockies Venture Club is a non-profit organization. RVC 2.0 envisioned in 2012 builds on RVC’s tradition of connecting investors and entrepreneurs and adds active angel groups, more sophisticated training and education, more events, a more diverse community and metric-driven action oriented approach to funding early stage companies.","http://www.denvergov.org/Portals/690/images/New/BizPlan%20Logos/RVCnew%20logo.JPG","rockiesventureclub.org", "AMS"],

["Silicon Valley Bank Financial Group","Silicon Valley Bank Financial Group provides diversified financial services to emerging, growth and established technology companies and the life science, venture capital and premium wine markets. Through its focus on specialized markets and extensive knowledge of the people and business issues driving them, SVB Financial Group provides a level of service and partnership that measurably impacts its clients’ success.","http://www.boulderstartups.org/wp-content/uploads/2011/04/svbfg-300x42.gif","http://www.svb.com/", "AMS"],

["Square 1 Bank","Square 1 Bank specializes in providing financial services to entrepreneurs and venture capitalists. We help growing companies and their investors navigate financial obstacles by providing access to funds and expertise. Our customized product offerings and unrivaled team of venture banking specialists provide a banking experience designed exclusively for you. As entrepreneurs, we have experienced what it takes to make a dream reality. We know the doubts. We know the late nights. We know the celebrations. We know that for an idea that’s never been done, flexibility is required. The unknown represents possibility not fear. We get it. We are entrepreneurs serving entrepreneurs.","http://www.boulderstartups.org/wp-content/uploads/2011/04/square1.jpg","https://www.square1financial.com/bankhome", "AMS"],


]

entities = [

["Colorado Office of Economic Development and International Trade (OEDIT)","The Colorado Office of Economic Development and International Trade (OEDIT) strengthens Colorado’s prospects for long-term economic growth by providing broad-based support to Colorado businesses. OEDIT fosters a positive business climate that encourages quality economic development through financial and technical assistance provided in support of local and regional economic development activities throughout the State of Colorado.","http://www.coloradosbdc.org/logos/oedit.jpg","http://www.colorado.gov/oed/industry-license/"],

["Boulder Small Business Development Center","The Boulder Small Business Development Center provides resources to help make your business successful, whether you are established, ready to grow, or just starting up.  The Boulder SBDC supports Boulder County businesses in three ways: workshops held throughout the year on a variety of topics,
confidential one-on-one consulting with experienced businesspeople, and
connecting clients to other valuable small business resources.","http://michaelcontiproductions.com/blog/wp-content/uploads/2010/02/pic32390.jpg","http://www.bouldersbdc.com/"],

["Innovation Center of the Rockies","The Innovation Center of the Rockies (ICR) connects talent with opportunity. Our core skill is getting the right people in the room. The ICR works closely with the Tech Transfer Offices at the University of Colorado, the Colorado School of Mines, the University of Denver, the University of Wyoming and Colorado State University to understand the commercial potential of their inventions. The ICR also assists high potential early stage companies.","http://innovationews.com/blog/wp-content/uploads/2012/10/innovation-center-of-the-rockies-featured.jpg","http://www.innovationcenteroftherockies.com/"],

["Mi Casa Women’s Business Center","The Mi Casa Women’s Business Center offers entrepreneurial training, individual business counseling, technology training and networking opportunities to help aspiring entrepreneurs and emerging businesses achieve their goals.","http://cps.regis.edu/blog/storage/2013/05/setting-an-example-in-nonprofit-leadership-regis-alum-ceo-of-mi-casa-resource-center.jpg","http://www.micasaresourcecenter.org/business-development/"],

["TiE Rockies","TiE Rockies is a chapter of TiE Global. We are one of 64 chapters in 18 countires with over 13,000 members. The mission and purpose of TiE Rockies is the same as TiE Global's, which is 'To Support the Entrepreneur' via our award-winning Mentoring Program, education, and networking. We have two levels of membership: Charter Membership and General Membership. Charter Membership is an exclusive, invitation-only club of successful business people focused on helping and supporting each other and the General Members. General Membership is open to all and TiE Rockies offers General Members over 100 programs each year designed to support their businesses and careers.","http://www.coloradotechnology.org/resource/resmgr/Company_Logos_360x261px_PNG_R-T/tie-rockies.png","https://rockies.tie.org/"],


]

providers = [

["Baker Hostetler","Baker Hostetler is celebrating its 95th anniversary. This milestone represents more than longevity. It offers a time to salute the many important clients and friends who have grown with us — often organizations we have served not just for years, but for decades.  Baker Hostetler’s clients include a variety of individuals and businesses achieving success globally, nationally, regionally and locally. Many are at the top of their market segments, and many are household names. Others are leaders of the future — companies with the aspiration and foresight to drive tomorrow’s high-growth industries. Every day, our lawyers help clients manage complex legal challenges and work toward achieving their strategic goals.","http://www.boulderstartups.org/wp-content/uploads/2010/12/bakerhostetler1-300x54.jpg","http://www.bakerlaw.com/aboutus/overview/", "legal"],

["BHGR","At BHGR, we offer the expertise and sophistication of a national law firm with the service and responsiveness of a boutique firm. Our approach is simple – our clients receive hands-on attention and the practical expertise of experienced lawyers who place a premium on delivering the highest quality legal advice in the most efficient and cost-effective manner as possible. Our lawyers are committed to excellence, creating long-standing personal relationships, accessibility, integrity, and providing pragmatic solutions to difficult problems. We take pride in the close relationships that we develop with our clients and playing an integral role as strategic partners in helping them reach their goals and providing solutions to problems.  This approach has made BHGR stand out among contemporary law firms.","http://www.boulderstartups.org/wp-content/uploads/2010/12/BHGR.jpg","http://www.bhgrlaw.com/", "legal"],

["Bryan Cave LLP","Bryan Cave LLP, an international law firm with offices in Boulder, Denver, Colorado Springs and 22 other worldwide locations, represents business, financial, institutional and individual clients, including startups, emerging-growth companies, cross-border public corporations, large and mid-market private companies, and partnerships.  Our clients include software, mobile, telecommunications, media, publishing and marketing companies as well as investors and energy, environment and natural resources companies, along with real estate organizations, and professional and nonprofit sports organizations, and tax exempt entities, including charitable, educational and religious organizations. Our services range from company formation and funding work to intellectual property protection and licensing as well as employment matters, counseling and litigation at the highest level. Bryan Cave’s innovative work in developing cost-effective, often novel, approaches to meet clients’ legal needs is often cited as among the industry’s best.  From working with clients to actively monitor 'legal spend' to applying technology to analyze high-profile matters in advance of litigation to developing alternative-fee structures tailored to a specific client’s needs, Bryan Cave is an innovation leader as well as legal-services leader in Colorado and beyond.","http://www.bryancave.com/files/FileControl/39143c6a-20df-494b-bb95-5d4ef44c6dbc/7483b893-e478-44a4-8fed-f49aa917d8cf/Presentation/File/BCcolorlogo-sm-highres.jpg","http://www.bryancave.com/", "legal"],

["Colson-Quinn","Colson-Quinn’s dedication to clients is not only our day-to-day commitment, it’s built into our structure and ideology. Leaving behind well-established business law practices, we chose to move to Boulder for quality of life both at home and in business. With business law experience in prominent Houston law firms, we’d seen the pitfalls of the traditional law firm model where clients were over-billed, overwhelmed and underappreciated. Realizing that our clients share our values for right relationships, respect, reasonable fees and results, we choose to be unique. We have created a firm dedicated to making a difference for our clients so that they can genuinely benefit from our collective experience.","http://www.colsonquinn.com/sites/181/images/logo.gif","http://www.colsonquinn.com/", "legal"],

["Cooley","Cooley represents hundreds of clients in a wide range of industries from offices in nine major commercial markets. We are counselors, strategists and advocates for the foremost private and public companies. We have a legacy of representing companies bringing to market breakthrough products and technologies and frequently argue cases that fall in new areas of law, brought about by technological developments. Our business and litigation practice reaches across a broad array of dynamic industry sectors, including technology, life sciences, clean tech, real estate, financial services, retail and energy. With 650 attorneys throughout the U.S., Cooley has the range and expertise to serve companies of all sizes to seize opportunities in today’s global marketplace.","http://www.cooley.com/images/logo_print.jpg","http://www.cooley.com/index.aspx", "legal"],

["Davis Graham & Stubbs","Davis Graham & Stubbs has provided legal support to emerging and established industries for the last 95 years. Throughout these years, DGS has ranked among the region’s most prominent law firms, consistently offering quality legal services to emerging and established businesses of the Rocky Mountain west. While the firm’s Denver headquarters and intermediate size allow a close personal relationship with local and regional clients, our technology and broad experience allow us to partner effectively with businesses and their investors throughout the world.","https://pbs.twimg.com/profile_images/378800000833508609/e5754ef4c740569673e064bd230fe0b0.png","http://www.dgslaw.com/Pages/default.aspx", "legal"],

["Docstoc","Docstoc is the premier online business for the best quality and widest selection of documents used to start, grow, and manage your professional life and small business. Docstoc provides the platform to upload and share documents with the world, and serves as a vast repository of free and for purchase legal, business, financial, technical, and educational documents that can be easily searched, previewed and downloaded.","http://www.boulderstartups.org/wp-content/uploads/2010/12/docstoc.jpg","http://www.docstoc.com/", "legal"],

["Entrepreneurial Law Clinic (ELC)","The Entrepreneurial Law Clinic (ELC) provides law students with practical experience in transactional law while offering free legal services to local businesses that lack access to venture capital or angel investor resources. The Clinic’s clients include graduate students, professors, local entrepreneurs, and start-up companies. Third-year Colorado Law students staff the Clinic during the academic year under the joint supervision of a full-time clinician and experienced attorneys from top law firms in Boulder and Denver. Students interact directly with clients to provide legal advice on a wide range of business-law issues including entity formation, intellectual property, employment, and contracts.", "No Image" ,"http://www.colorado.edu/law/academics/clinics/entrepreneurial-law-clinic", "legal"],

["FindLaw Intellectual Property Center","The FindLaw Intellectual Property Center provides information and resources to help businesses protect their own intellectual property and avoid infringing on the intellectual property rights of others. You will find practical and legal tips on registering and using copyrights, patents, and trademarks.","http://www.boulderstartups.org/wp-content/uploads/2010/12/Findlaw.jpg","http://smallbusiness.findlaw.com/intellectual-property/", "legal"],

["Gross Cutler Seiler Dupont","Gross Cutler Seiler Dupont is a corporate, business and intellectual property law firm that counsels clients in the full range of corporate and securities matters, including public and private financing transactions, mergers and acquisitions, strategic corporate relationships, corporate governance, employee incentive programs and executive hiring.  We also focus on branding, advertising, trademark, copyright and trade secret topics, as well as disputes and expert witness work in these fields.","http://www.boulderstartups.org/wp-content/uploads/2010/12/4844-7678-6969-1-GCSD_Logo.jpeg","http://gcsdlaw.com/", "legal"],

["Holland & Hart","With our firm-wide resources, local presence, and coordinated efforts, Holland & Hart delivers integrated legal solutions to regional, national, and international clients of all sizes, from emerging businesses to Fortune 500 corporations. Since its inception in 1947, Holland & Hart has grown into a firm of more than 400 lawyers in 15 offices in Colorado, Wyoming, Idaho, Montana, Nevada, New Mexico, Utah, and the District of Columbia. In 2007 and 2008, Holland & Hart was named the best corporate law firm in Denver according to a survey of corporate directors in Corporate Board Member magazine. It is also the largest law firm based in the Mountain West ranked on The American Lawyer‘s list of the top 200 firms in the United States.","http://www.coloradotechnology.org/resource/resmgr/Company_Logos_360x261px_PNG_F-L/Holland-&-Hart.png","http://www.hollandhart.com/index.cfm", "legal"],

["Hogan Lovells","Hogan Lovells provides legal services based on the principles of teamwork, collaboration, and commitment to client service. We take time to understand our clients’ businesses so we can work as an extension of their team. We help them navigate a challenging global landscape through focused, innovative, high quality service. Clients come first at Hogan Lovells. Building on the foundations of our previous success as two firms, Hogan & Hartson and Lovells, Hogan Lovells is deeply rooted in the largest and most developed markets in the United States and Europe and has an established presence in the fastest growing regions of the world, including Asia, Latin America, and the Middle East.","https://www.cardiffstudents.com/pageassets/activities/society/law/HoganLovells_2013.jpg","http://www.hoganlovells.com/", "legal"],

["Hutchinson, Black and Cook","Hutchinson, Black and Cook has provided legal services to businesses and individuals in Colorado since 1891.  We nurture start-ups and give them the time, attention and support they need to grow into nationally recognized companies that are integral to the Boulder community.  Our longevity gives the firm a unique understanding of Boulder’s business environment and the Colorado community as a whole.  HBC’s experience can make the difference in recognizing opportunities, anticipating obstacles and devising creative solutions.  Our tradition of service places the highest priority on providing our clients with individualized attention and legal work of the best quality – aggressively, efficiently, and economically.  With lawyers from the top ranks of the best schools, we offer the sophistication of a large law firm practice – deal for deal, case for case – with the cost-effectiveness and personal service of a smaller firm.","http://www.boulderstartups.org/wp-content/uploads/2010/12/logo-1.gif","http://www.hbcboulder.com/", "legal"],

["Kendall, Koenig & Oelsner","Kendall, Koenig & Oelsner is a corporate and business law boutique focusing on transactional legal matters, including mergers and acquisitions, securities, venture capital, credit finance, legal entity formation and commercial contracts. The firm was created for businesses, financial institutions, investors and individuals that have been historically underserved by the legal industry. We are committed to providing the highest level of attentive service and expertise to our clients. Just because a client or a project is small in size, does not mean that sophisticated, expert legal service is unwarranted.","http://kkofirm.com/images/kko_logo.png?1381181007","http://www.kkofirm.com/index.html", "legal"],

["Lathrop & Gage LLP","Lathrop & Gage was founded in 1873 on the heartland principles of honor, service, trust and value. We are committed to serving our clients in the same unwavering manner today. While our attorneys have amassed many successes in the past 130+ years, the accomplishment of which we are most proud is our continuing representation of our first-ever client, now known as the BNSF Railway Co. Indeed, Lathrop & Gage has enjoyed success in the 19th, 20th and 21st centuries because we are committed to providing excellent talent, service and results, and adapting to changing business environments and technology.","http://www.boulderstartups.org/wp-content/uploads/2010/12/lathropandgage.jpg","http://www.lathropgage.com/about.html", "legal"],

["Lefort LLC","Lefort LLC brings twenty years of business and cutting edge IP legal experience that can assist any company from startup to established. Lefort LLC provides traditional patent and trademark services. In addition to being a full service Intellectual Property law firm, Lefort LLC can act as a client’s in-house IP counsel or IP strategist and help companies identify, develop, leverage and protect what may be their most significant assets. By retaining Lefort LLC,  clients will deal directly with a former patent litigator and experienced in-house Intellectual Property attorney who can provide a comprehensive range of IP services and IP consulting upon which your company can capitalize.","http://www.boulderstartups.org/wp-content/uploads/2010/12/Lefort-LLC-IP-Attorney-Logo.png","http://www.lefortiplaw.com/", "legal"],

["LegalZoom","LegalZoom is an easy-to-use, online service that helps people create their own legal documents. The company’s mission is to set new standards for convenience and service in an industry not typically known for great customer care, making it easy for anyone to create a last will, incorporate a business, trademark a name or take care of other common legal matters. The goal is not simply to provide a smart, cost-effective alternative—it’s to make sure everyone gets the legal protection they need.","http://www.boulderstartups.org/wp-content/uploads/2010/12/legalzoom.jpg","http://www.legalzoom.com/", "legal"],

["Moye White","Moye White offers strategic representation in complex commercial transactions and disputes. Our clients range from entrepreneurs and startups to mid-sized and established corporations, organizations, and associations. We also provide local counsel services for many national law firms. Our attorneys, paralegals, and administrative staff collaborate in a unique, team-oriented environment. We take the time to get to know our clients, understand their interests, and help define their future goals.","http://planetyang.com/wp/wp-content/uploads/2009/10/moye.jpg","http://www.moyewhite.com/default.aspx", "legal"],

["Roberts & Olivia, LLC","Roberts & Olivia, LLC is a boutique business law firm representing clients in transactional matters, including formation of legal entities, venture capital and other private placements, commercial lending, mergers and acquisitions, real estate, employment matters, intellectual property matters and other commercial contracts. We are located in Boulder, Colorado and serve clients along the Front Range of Colorado and beyond in many industries, including technology, software, life sciences, energy, natural resources and retail. We represent clients of all sizes from early stage, start-up companies to established privately and publicly held companies.","http://wrrlaw.com/images/logo.gif","http://www.wrrlaw.com/index.html#", "legal"],

["Spanish Legal Forms","Spanish Legal Forms, powered by FindLegalForms.com, provides a comprehensive library of legal documents, papers and business forms to protect a business owner’s rights as well as save time and money. With forms from Accounting to Wills, this also includes an active question and answer forum for those seeking quick advice on common questions.","http://www.boulderstartups.org/wp-content/uploads/2010/12/spanishlegalforms-300x33.jpg","http://www.spanishlegalforms.com/", "legal"],

["U.S. Patent and Trademark Office","The U.S. Patent and Trademark Office has created a web site to help small businessesconsider the benefits of strong IP protection – both in the United States and overseas – and decide whether it is right for them. This site includes important information on whether and when to file for intellectual property protection, what type of protection to file for, where to file, and how to go about it. While every IP-based business is vulnerable to piracy and counterfeiting, small businesses can be at a particular disadvantage because they lack the resources and expertise available to larger corporations. Small businesses may also often lack the familiarity with the process of protecting intellectual property: research conducted in the spring of 2005 by the U.S. Patent and Trademark Office (USPTO) indicates that only 15 percent of small businesses that do business overseas know that that a U.S. patent or trademark provides protection only in the United States. It has never been more essential for you to consider patenting your idea or registering your name as a trademark, especially if you are a small business owner or are starting a small business.","http://www.boulderstartups.org/wp-content/uploads/2011/04/USPTOlogo.gif","http://www.uspto.gov/smallbusiness/", "legal"],

["West Venture Law","West Venture Law is a Boulder, Colorado based law firm specializing in the areas of business and corporate law, complex commercial transactions, technology law, and commercial disputes and litigation.  Many of our attorneys have real world business experience, having founded and managed a variety of non-legal ventures in addition to practicing law.  We assist entrepreneurs, startups, and growth stage companies achieve their goals and objectives by anticipating and overcoming roadblocks with creative entrepreneurial lawyering and a strategic business oriented approach.  We also believe strongly in our community, providing hundreds of hours of pro bono work every year to community-oriented and non-profit ventures.  West Venture Law prides itself on the dedication, experience and effectiveness provided in achieving each client’s unique goals.","http://www.boulderstartups.org/wp-content/uploads/2010/12/Logo-w-Text.png","http://www.westventurelaw.com/", "legal"],

["AngryBovine","AngryBovine is a multi-disciplinary creative studio based in Boulder, Colorado. We specialize in brand development and interactive, but believe in putting the right ideas and thinking to work in the mediums that it requires to be successful, wherever that may be, in print, online and everywhere in between. Our design based approach is really about delivering creative that builds brands, communicates clearly and solves business problems. We partner with our clients to help them reach and exceed the objectives quickly and affordably.","http://openheartco.org/wp-content/uploads/2013/09/angry_bovine.png","http://www.angrybovine.com/", "design"],

["Dojo4","The culture we foster at dojo4 is integral to who we are and how we do business. It's important to us that our work is impactful, effective, meaningful and sustainably rewarding. Our workplace aims to be one that promotes physical and mental health, joy, humor and compassion. dojo4 is built to provide the basis for engaging challenges, fostering creative and intellectual development, and to be a real source of support for our clients, ourselves and our families. We believe that sane and supportive workplaces can be the building blocks for stability and innovation in our greater culture.","http://dojo4.com/images/og.png","http://dojo4.com/", "design"],

["Find Freelancers","An Easy way to find freelance developers in Colorado.","https://pbs.twimg.com/profile_images/344513261566092191/6bd30fb49c0a903306aeb926b77b57b2.png","http://bdnt.org/freelancers", "design"],

["Mondo Robot","Mondo Robot is a creative digital agency based in Boulder Colorado. We rock web sites, games, strategy, bikes, motion, tequila, video, code, logos, tacos, mobile, music, new identities, IPA’s and sweet Colorado POW.  Not to mention, we’re a hell of a lot of fun to work with.","https://www.adcd.com/wp-content/uploads/2013/06/75361_497542153593_1423632_n.jpg","http://www.mondorobot.com/", "design"],

["Pivotal Labs","We provide expertise in three competencies equally crucial to delivering the best product: design, development and product management. Integrating these roles is a key part of our agile process. This cross-functional collaboration between designers, developers and product managers brings out the best features, design and product.","http://www.devleague.com/img/employers/PivotalLabs.jpg","http://pivotallabs.com/", "design"],

["Quick Left","We are problem solvers by nature, we just happen to be engineers and designers by trade. We pride ourselves on bringing real advice to the table, backed by extensive experience, and an excellent ability to listen to our clients' needs.","http://innovationews.com/blog/wp-content/uploads/2014/01/Quick-Left-featured1.jpg","http://quickleft.com/", "design"],

["Rage Digital","Rage Digital provides global brands, SMB and startups with a one-stop shop for full stack, iOS and Web App: Concept, Design and Development. We specialize in highly design-centric, mobile and web Apps for clients that require the level of sophistication and polish their brands deserve and customers expect. No project is too big or too small, we love them all!","http://b.vimeocdn.com/ts/199/867/199867376_640.jpg","http://ragedigital.com/", "design"],

["Slice of Lime","Slice of Lime offers advanced coding and back-end development for your web projects. Whether you want a web-standards compliant website, a simple lead generation form, a dynamically driven Flash site, we can help. Slice of Lime can build custom content management systems to easily update sections of your website without needing to know a line of code.","http://www.boulderstartups.org/wp-content/uploads/2010/12/sliceoflime2.jpg","http://www.sliceoflime.com/", "design"],

["Viget","We’re a team of 65 passionate, dedicated individuals who love collaborating to make exceptional digital products and platforms with our clients.","http://1.bp.blogspot.com/-vw0EembULTw/TzrP2NMfnqI/AAAAAAAAAJs/T4uOKQ-zrus/s1600/Viget.jpg","http://viget.com/", "design"],

["Find Freelancers","An Easy way to find freelance marketers in Colorado.","https://pbs.twimg.com/profile_images/344513261566092191/6bd30fb49c0a903306aeb926b77b57b2.png","http://bdnt.org/freelancers", "marketing"],

["Metzger Associates","Metzger Associates is one of the most respected strategic communications firms in the Rocky Mountain region, with a national reputation for results, creativity, aggressive execution and out-of-the-box strategic thinking. We were one of the first agencies in the country to apply New Media technologies to communicate clients’ key messages. We position our clients as thought leaders and innovators, and our goal is to improve their bottom lines as well as their visibility.","http://www.boulderstartups.org/wp-content/uploads/2010/12/metzger-300x79.png","http://www.metzgerblog.com/", "marketing"],

["Room 214","Room 214 is a social media marketing agency founded in 2004 – but the real story began with a teen-aged friendship that brought two people from sharing a dorm room their freshman year in college (guess the room number) to running an award-winning agency whose success remains about helping people and companies to be seen and heard online. Serving organizations desiring to go deep with social media, Room 214 helps you engage your customers, humanize your brand and build upon what works. If leadership in your market is the goal, this agency should be your agency.","http://www.timebussystems.com/wp-content/uploads/2012/09/Room2141.jpg","http://www.room214.com/", "marketing"],

["Slice of Lime","Slice of Lime offers advanced coding and back-end development for your web projects. Whether you want a web-standards compliant website, a simple lead generation form, a dynamically driven Flash site, we can help. Slice of Lime can build custom content management systems to easily update sections of your website without needing to know a line of code.","http://www.boulderstartups.org/wp-content/uploads/2010/12/sliceoflime2.jpg","http://www.sliceoflime.com/", "marketing"],

["Trada","Trada is the world’s first and only crowdsourced PPC services marketplace, where a community of more than 1,000 paid search experts – Optimizers – work and are paid on their performance. With multiple Optimizers working on a campaign at the same time, Trada’s advertisers and agencies can save time and explore new markets. The diversity of thinking and sheer force of humanpower that comes from a group of people working in a market gets results an individual or a piece of software could simply never achieve.","http://www.boulderstartups.org/wp-content/uploads/2010/12/trada1.png","http://www.trada.com/", "marketing"],

["Victor and Spoils","Hello. Meet the Ad Agency known as V&S.","http://craigphares.com/blog/wp-content/uploads/2009/11/mob-590x590.jpg","https://www.victorsandspoils.com/", "marketing"],

["AVL Growth Partners","AVL Growth Partners (AVL) is a unique professional services firm that delivers finance and accounting advisory expertise to small and medium sized growth businesses.","https://pbs.twimg.com/profile_images/2286985993/AVL_Logo1.jpg","http://avlgrowth.com/", "accounting"],

["BlackWood Finance & Accounting","BlackWood Finance & Accounting provides comprehensive outsourced finance and accounting services to small and start-up companies. We offer the full spectrum of services from transaction processing to financial management and strategic financial planning. BlackWood’s goal is to help clients succeed by allowing them to plug into an existing finance and accounting department thereby enabling them to better focus on their other critical success factors.","http://www.boulderstartups.org/wp-content/uploads/2011/08/blackwood_logo_final.jpg","http://www.blackwoodfinance.com/", "accounting"],

["Ehrhardt Keefe Steiner & Hottman","Since its founding in 1978, Ehrhardt Keefe Steiner & Hottman PC (EKS&H) has grown into the largest Colorado-based accounting and business consulting firm. Over the last decade, we’ve grown consistently at an unprecedented rate compared to other accounting and business consulting firms that serve Denver, Fort Collins, Boulder and surrounding markets throughout the Rocky Mountain region. The continued growth of our firm demonstrates we’re trusted business advisors to our clients.","http://www.boulderstartups.org/wp-content/uploads/2011/08/EKSandH.jpg","http://www.eksh.com/", "accounting"],

["Kurtz Fargo LLP","Kurtz Fargo LLP provides high quality assurance, tax and advisory services to emerging growth, small and mid-sized businesses.  The Firm is committed to delivering high quality expertise, outstanding client service and utilizing cutting edge technology and research tools.","http://www.boulderstartups.org/wp-content/uploads/2011/08/kurtzfargo.jpg","http://www.kurtzfargo.com/what-we-do/", "accounting"],




]

spaces = [

["Boulder Digital Arts","For over ten years, BDA has been empowering creatives and entrepreneurs with community-powered, in-person classes & workshops that are focused on practical skills and taught by industry professionals. Whether you work in film, technology, design, photography, or business, we seek to empower your creative process with education, community and collaboration.","https://pbs.twimg.com/profile_images/378800000790395972/e44f2f3ab91a4e84c4f790cc247face6.jpeg","http://www.boulderdigitalarts.com/", "space"],

["Fuse at the Riverside","Sit by Boulder Creek on our one-of-a-kind patio, check your e-mail as you enjoy a cappuccino in our bustling cafe, or go whiteboard out an idea with your coworkers in our private shared workspace. Choose the work environment that suits their needs and take full advantage of the creative collisions that are engendered by the open and collaborative nature of the Fuse community.","http://boulderfuse.com/wp-content/uploads/2013/03/FuseATRLogo-01.png","http://boulderfuse.com/", "space"],

["Galvanize","Physical proximity to other doers, makers and innovators is important. There is no manual for entrepreneurial success. It’s a journey. A journey that is only limited on your ability to learn and grow. This type of learning comes from doing—from experience. The skills, connections, and mentorship your journey requires are coalesced here.","http://startupphenomenon.com/2013/wp-content/uploads/2013/06/galvanize-2.jpeg","galvanize.it", "space"],

["Impact HUB Boulder","Impact Hub Boulder provides a productive workspace, effective programming, and a collaborative network to accelerate our members’ efforts towards creating positive impact in the world. Become a member and enjoy our 10,000 square foot coworking space, professional and welcoming community, informative events, and many other benefits. Drop in for a trial day, rent a conference room, hold your event here, or simply stop by for a tour.","http://www.bcorporation.net/sites/default/files/styles/company-logo-full/public/impact%20hub%20boulder.png?itok=eMyYT1O-","http://www.impacthubboulder.com/", "space"],

["Scrib","Scrib (short for Scribble) is a coworking location in the heart of Boulder designed to stimulate connections of like-minded creatives, consultants, entrepreneurs, startups and freelancers. It’s a community that goes beyond desk space and drives growth and innovation by connecting people. Located at 2060 Broadway (Broadway & Spruce), Scrib is 5,000 square feet of shared work space designed with different zones to make you as productive as possible. Come write on the dry erase walls, brainstorm with a team in the cafe or present to a client in the conference room.","http://photographyjulia.com/blog/wp-content/uploads/2012/02/Scrib_Interiors_2012_0292.jpg","http://scrib.co/", "space"],

["Spark Boulder","Spark Boulder is a space for entrepreneurship, designed and created by students to foster creativity, cultivate talent, and accelerate innovative ideas. Spark Boulder is a student entrepreneur’s playground that will allow Boulder and the University of Colorado to remain at the forefront of student innovation and entrepreneurship.","http://sparkboulder.com/wp-content/uploads/2013/10/building-small-621x320.jpg","http://sparkboulder.com/", "space"],

["Boomtown","This Spring, 10 startups will participate in an intense 12-week accelerator in Boulder, CO. Boomtown offers to startups the best of what makes Boulder one of the best startup cities in the world, with the highest density of startups per capita on the planet. You’ll be mentored by seasoned investors, engineers, designers, and marketers (and did we mention that the New York Times called Boulder the New Madison Ave?) all focused on taking your startup to the next level.","https://s3.amazonaws.com/photos.angel.co/startups/i/331404-9e314a716b35ecf475af2b8b711ffad5-medium_jpg.jpg?buster=1390887738","http://www.boomtownboulder.com/", "accelerator"],

["Techstars","Techstars is the #1 startup accelerator in the world.","http://innovationews.com/blog/wp-content/uploads/2012/10/techstars-logo-small.jpg","http://www.techstars.com/program/locations/boulder/", "accelerator"],

["Unreasonable Institute","We exist to give entrepreneurs tackling the world’s greatest challenges an 'unreasonable advantage.' How do we do this? Each year, we match a dozen carefully vetted ventures from around the world with 50 mentors (including the Chairman of Whole Foods, a guy who’s helped over 20 million people out of poverty, and a Time Magazine Hero of the Planet) and 100+ funders at 5-week bootcamps.After the five weeks, we provide entrepreneurs with pro-bono executive coaches, support in sustaining their relationships with relevant mentors and funders, guidance and connections from a dedicated team whose main job is to get these ventures funded, and access to our network of 250+ partners, 100+ mentors, 250+ funders, and 82 ventures from 37 countries. Our goal is to help each of these ventures scale up to meaningfully impact the lives of over 1 million people each.","http://blueseed.co/wp-content/uploads/unreasonableinstitute-big.png","https://unreasonableinstitute.org/", "accelerator"],

]


class_list.each do |name, code, description, discipline |
  Course.create( name: name, code: code, description: description, discipline: discipline )
end

student_groups.each do |name, description, photo, website |
	StudentGroups.create(name: name, description: description, photo: photo, website: website)
end

funding.each do |name, description, photo, website, funding_type|
	Funding.create(name: name, description: description, photo: photo, website: website, funding_type: funding_type)
end

entities.each do |name, description, photo, website |
	Entities.create(name: name, description: description, photo: photo, website: website)
end

providers.each do |name, description, photo, website, provider_type|
	Providers.create(name: name, description: description, photo: photo, website: website, provider_type: provider_type)
end

spaces.each do |name, description, photo, website, space_type|
	Space.create(name: name, description: description, photo: photo, website: website, space_type: space_type)
end



