# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


class_list =  [

["Introduction to Entrepreneurship", "ESBM 3100", "Introduces non-business students to the multiple facets of entrepreneurship and the entrepreneurial process. Entrepreneurship is a process of fundamental transformation: from innovative idea to enterprise and from enterprise to valuethus, entrepreneurship is more than a business practice. Innovation is central to this process and students will be challenged to develop creative solutions to a problem or need. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["Principles of Business for Entrepreneurs", "ESBM 3200", "Provides non-business students with a basic understanding of the business principles required to start and grow an entrepreneurial venture. It is intended for individuals who have not taken a marketing, accounting or finance course. This course will focus on two aspects of business that are critical to the success of any new venture: marketing and financial management. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["Writing a Venture Plan", "ESBM 4100", "Requires non-business students to engage in a rigorous, thoughtful and challenging process essential to planning a new venture. Using their own concept, students will develop a strategy to start and grow a venture. Communicating the plan is an essential element of this course and students will learn when and how to write a plan and make effective presentations. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Business"],
["Introduction to Entrepreneurship for Engineers", "ESBM 3100-3", "Introduces non-business students to the multiple facets of entrepreneurship and the entrepreneurial process. Entrepreneurship is a process of fundamental transformation: from innovative idea to enterprise and from enterprise to valuethus, entrepreneurship is more than a business practice. Innovation is central to this process and students will be challenged to develop creative solutions to a problem or need. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Entrepreneurship"],
["The Entrepreneurial Artist", "MUSC 4988/5988", "Learn the core principles of entrepreneurship, such as idea formation, venture models, opportunity assessment, market analysis, and strategies for launching a venture, and apply them to their own entrepreneurial ideas. Lectures, projects, entrepreneur interviews, and case studies will culminate in a feasibility study for an original entrepreneurial concept. Recommended prereq., MUSC 4918. Same as MUSC 5988.", "Music"],
["Building Your Music Career", "MUSC 2918/5918", "Students acquire the practical skills they need to build their career as professional musicians, as well as explore the many options for putting their music education to work in the marketplace. Students will also explore the state of live music-making today and explore ways to maintain relevance for themselves and their art in an ever-changing world. Formerly MUSC 4918. Restricted to College of Music majors only. Prerequisites: Restricted to College of Music undergraduate students only.", "Music"],
["Startup Essentials for Software Entrepreneurship", "CSCI 4830/7000", "Students learn about agile methodologies in software development in regard to entrepreneurship", "Engineering"],
["Business Methods and Economics for Engineers", "EMEN 4100", "Covers cost concepts, financial statements, and the company economic environment. Includes concepts and methods of analysis of the time value of money, comparison of project alternatives before and after taxes, cash flows, replacement analysis, risk management, and financial cash statements. Restricted to junior or senior in the College of Engineering and Applied Science. Prerequisites: Restricted to students with 57-180 credits (Junior or Senior) College of Engineering students only.", "Engineering"],
["Tech and Entrepreneurship in the Developing World", "EMEN 4830", "", "Engineering"],
["Technology Ventures and Marketing", "EMEN 5090", "Acquiring marketing know-how is essential for engineers interested in technology and product development. Students learn the basic tenets of marketing with emphasis on developing a technology innovation into a commercially successful product. Special attention given to customer development as a key aspect of product development. Course designed to be of interest to engineers in existing companies and startups. Highlighted will be in-depth discussions of real-world case studies and providing the student with marketing strategies for the high tech environment. Non-EMP students require instructor permission. Restricted to graduate students in Engineering Management Program (EMEN) only. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only."],
["Entrepreneurial Business Plan Preparation", "EMEN 5825", "Instructs students in the necessary elements of a business plan and how to prepare a complete, well-written plan for an entrepreneurial business venture. Students work in teams to create a business concept and take it through business plan completion. Recommended prereq., EMEN 5020 or equivalent. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Lean and Agile Management", "EMEN 5500", "Operations Management has evolved and broadened from a sole focus on the manufacturing of hardware to a more universal set of concepts, management methods, and practical tools spanning manufacturing, supply chains, product development, software development, project management, support services, and accounting. This new approach can best be described as lean and agile management. Credit not granted for this course and OPIM 6080. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Entrepreneurial Business Plan Preparation", "EMEN 5825", "Instructs students in the necessary elements of a business plan and how to prepare a complete, well-written plan for an entrepreneurial business venture. Students work in teams to create a business concept and take it through business plan completion. Recommended prereq., EMEN 5020 or equivalent. Non-EMP students require instructor permission. Prerequisites: Restricted to graduate students in Engineering Management Program (EMEN) only.", "Engineering"],
["Entrepreneurial Innovation and Public Policy", "LAWS 5201", "Explores cutting edge questions around entrepreneurship, including being an entrepreneur, leadership and what makes a great founding team, building and scaling a business, entrepreneurial communities, financing entrepreneurial companies, leadership in government, entrepreneurship and innovation policy. Restricted to Law students only. Prerequisites: Restricted to Law students only.", "Law"],
["Philosophy of Entrepreneurship", "LAWS 6271", "", "Law"],
["Venture Capital and Private Equity", "LAWS 7271", "Provides overview of the legal and financial principles to represent privately held companies, their founders and managers, and their investors. Emphasizes transaction structuring rather than judicial opinions. Includes the organization and financing of start-ups, structuring buyout transactions, exit strategies, legal organization of investment funds and other financial intermediaries. Discusses the relevant regulatory landscape, including securities law, bankruptcy, ERISA, and tax law.", "Law"],
["Entrepreneurial Law Clinic", "LAWS 7619", "Advise indigent clients who need legal services in the founding of their business or not-for-profit firms, registering LLCs, and drafting employment and intellectual property agreements. Prereq., two of the following courses: Agency Partnership and the LLC, Corporations, Securities, Seminar on Corporate Law, Law and Finance for Entrepreneurs, Accounting Issues for Lawyers, Patent Law, Trademark, and International Business Transactions. Prerequisites: Restricted to Law students only.", "Law"],
["Principles of Business for Entrepreneurs", "ESBM 3200", "Provides non-business students with a basic understanding of the business principles required to start and grow an entrepreneurial venture. It is intended for individuals who have not taken a marketing, accounting or finance course. This course will focus on two aspects of business that are critical to the success of any new venture: marketing and financial management. Restricted to non-Business majors with 60-180 units completed. Prerequisites: Restricted to non-Business majors with 60-180 units completed.", "Business"],
["Entrepreneurial Environments", "ESBM 3700", "Introduces entrepreneurship. Addresses opportunity recognition, target markets, industry analysis, business model identification, sources of funding, managing rapid growth, and writing feasibility studies. Examines alternative forms of entrepreneurship such as franchising, corporate entrepreneurship, family business, and social entrepreneurship. Prereqs., BCOR 2000, 2050, 2100, 2150, or BCOR 2000, 2200, 2300, 2400. Restricted to students with 52 hours completed. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Entrepreneurial Finance", "ESBM 4570", "Focuses on the financial concepts, issues, methods, and industry practices relevant to entrepreneurial decision makers. Addresses a variety of topics including financial valuation, various sources of funds, structures and legal issues in arranging financing, the private and public venture capital markets, and preparation for, and execution of, an initial public securities offering. Provides an understanding of the segments of the capital markets specializing in start-ups and growth financing. Prereq., BCOR 2200. Restricted to Business majors with 52-180 units completed. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Business Plan Preparation", "ESBM 4830", "Work as part of a small team, with the focus on the process of creating a plan from the business concept and model through all of the elements of a professionally written business plan document. Prereqs., ESBM 3700 and 4570. Same as EMEN 4825. Prerequisites: Restricted to Business majors with 52-180 units completed.", "Business"],
["Entrepreneurship", "MBAX 6100", "Examines the environments of entrepreneurial firms from start-up to development of ventures. Allows students to assess their fit with entrepreneurial firms. Key element is learning the process of determining the difference between ideas and commercializable opportunities through feasibility analysis and plans. Prereq., MBAC 6020 or instructor consent. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Entrepreneurial Finance", "MBAX 6110", "Addresses a variety of topics including financial valuation, various sources of funds, structures and legal issues in arranging financing, the private and public venture capital markets, and preparation for, and execution of, an initial public securities offering. Prereq., MBAC 6020. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Business Plan Preparation", "MBAX 6170", "Completion of a sophisticated business plan within task groups from concept through all the elements of a professionally written business plan. Provides students high interaction with businesses and entrepreneurs. Prereq., MBAC 6020 and MBAX 6100, or instructor consent. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Start Up Execution", "MBAX 6180", "Covers a variety of topics in applied entrepreneurship, including the steps required to legally launch a business and procedures for executing standard business functions (organization, marketing, sales, advertising, operations, team building, and finance) with minimal resources (cash, personnel, and equipment). Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Projects in Entrepreneurial Companies", "MBAX 6190", "Limited to 12 students per section, each student is matched with an entrepreneurial company to complete a project that is key to company strategy. Students experience total company environment from the top management level through attending management meetings and interacting with cross-functional managers and employees. E-mail and face-to-face meetings result in discussing opportunities and issues resulting from experiences in companies. Prereq., MBAX 6100. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["New Product Development", "MBAX 6360", "Provides a better understanding of the new-product development process, highlighting the inherent risks and strategies for overcoming them. Using a combination of lectures, cases, and a project, this course examines the process of designing, testing, and launching new products. Emphasizes the interplay between creativity and analytical marketing research throughout the development process. Also covers branding issues, such as brand extensions and their impact on brand equity. Prereq., MBAC 6090. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Environmental Entrepreneurship", "MBAX 6130", "", "Business"],
["Entrepreneurship and the Venture Capital Process", "MBAX 6805", "This course will be articulated into two main parts, tightly interrelated: Entrepreneurship and the Venture Capital Process. The first part has the objective to lead the students to understand what venture capital is, how it works, how you structure capital raising, and how it helps entrepreneurial initiatives. The second part concerns how venture capitalists manage their operations, secure investment deals, and maintain their portfolios. Prereqs., MBAC 6011, 6020, 6031, 6040, 6060, 6080, and 6090. Restricted to LAWS students and graduate students in business. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Social Entrepreneurship for Emerging Markets", "MBAX 6845", "Social entrepreneurs adopt business approaches to solving global, social and environmental problems that have not been effectively addressed by government, business or traditional nonprofits. The course provides a framework for student teams to assist social entrepreneurs in developing countries, helping them achieve their social mission while operating sustainably and with measurable impact. Prereqs., MBAC 6010, 6060, and 6090. Recommended prereq., MBAX 6170. Prerequisites: Restricted to Master of Business Admin (MBAD), MBA with Dual Degree (DMBA), Joint Juris Doctor/MBA (JMBA) or Professional MBA Program (PMBA) majors only.", "Business"],
["Mobile App Development", "ATLS 4519", "Analyzes special interest areas of multidisciplinary technology, arts and media research and practice. May be repeated up to 9 total credit hours. Prereq., instructor consent. Recommended prereqs., ATLS 2000, ATLS 3010, and ATLS 3020. Same as ATLS 3519, 5519 and 6519.", "Engineering"],






]

student_groups = [

["Active Entrepreneurs","CU Student Entrepreneurship Collaboration.","active.png","https://www.aecuboulder.com"],

["Boulder Beta Alpha Psi","Leeds Business Fraternity.","BAP.png","http://leeds.colorado.edu/club/betaalphapsi"],

["Boulder Creatives","Cross-campus student club/nonprofit organization performing high-level design, marketing, and advertising work for Colorado companies.","Lcreatives.png","http://bouldercreatives.com"],

["Business Law Association (BLA)","Provides law students with contacts and info about the business world.","No Photo URL","https://www.colorado.edu/law/students/organizations"],

["Collegiate Social Impact Initiatives (CSII)","We are college students working as effective and sustainable agents of positive social impact.","CSII.png","http://csii.colorado.edu"],

["CU Biotech Club","Student organization for business, engineering, and life sciences students interested in biotechnology.","Biotech.png","http://www.cubiotechclub.com/"],

["CU CEO","Undergraduate entrepreneurship club for Leeds School of Business students.","CEO.png","http://leeds.colorado.edu/club/ceo"],

["CU Energy Club","Interdisciplinary entrepreneurship club for students interested in the energy industry.","energy.png","http://cuenergy.org"],

["CU New Venture Challenge (NVC)","Interdisciplinary cross-campus business competition.","nvc.png","http://cunvc.org"],

["CUSkills","Connecting students to peers who can help.","cuskills.png","http://cuskills.com"],

["CU Women In Business Club","Leeds focused, student club for females in business.","No Photo URL","https://leeds.colorado.edu/club/mbawomeninbusiness"],

["Entrepreneurial Solutions","Leeds focused student consulting organization.","EntSolutions.png","http://leeds.colorado.edu/club/entrepsolutions"],

["InnovateCU","Software Development and Computer Science Club.","innovateCU.png","http://innovatecu.com"],

["Leeds Entrepreneurship Alliance (LEA)","MBA student club, Leeds focused.","LEA.png","https://cuboulderlea.wordpress.com/"],

["The Silicon Flatirons Student Group","Interdisciplinary research center for Law Students and ITP focusing on entrepreneurship.","silicon.png","http://silicon-flatirons.org/"],

["StartUp CU","Cross-campus entrepreneurship club for new startups.","Startupcu.png","http://startupcu.com"],

["TEDxCU","CU’s own TEDx.","TED.png","http://tedxcu.com"],




]

funding = [

["Access Venture Partners","Access Venture Partners is an early stage venture capital fund. Together over the past 14 years, the partners at Access Venture Partners have invested in over fifty early stage companies and have served as founders and early executives of numerous companies. Through this experience we have built an understanding of how to navigate the challenges associated with building successful companies and drive them to success.","http://www.boulderstartups.org/wp-content/uploads/2011/04/access-206x300.gif","http://www.accessvp.com/index.php", "VC"],

["Altira","Altira is committed to building companies that will transform the energy sector. Founded in 1996 with the sole purpose of successfully investing in the energy technology sector, Altira Group focuses on growth technology companies spanning the energy value chain from source to resource, and takes an active lead investment role by providing solid follow-on capabilities.","http://www.boulderstartups.org/wp-content/uploads/2011/04/altira_nav2_r1_c2.gif","http://www.altiragroup.com/index.html", "VC"],

["Boulder Ventures","Our investment approach has remained consistent for more than fifteen years: We invest in early stage information technology and life science companies in Colorado and the Mid-Atlantic region. We invest in serial entrepreneurs with the proven ability to create and lead successful teams. We partner with leading venture capital funds to form investor syndicates that bring experience as well as capital to market-leading companies.","http://www.highway12ventures.com/wp-content/uploads/2011/10/Boulder_ventures-logo-AC128D79E5-seeklogo.com_.gif","http://www.boulderventures.com/", "VC"],

["Point B Capital","Point B Capital is more than an investor.  Their relationship with Point B gives them unique insight into winning companies—with over 15 years of helping them grow and thrive. They make equity investments and manage complex deals that capture value and leverage the rich relationships that Point B has developed since 1995. Their network includes more than 300 clients across 27 industries. They build value for both portfolio companies and Point B’s broader client base by bringing the two together for mutual benefit.","http://www.boulderstartups.org/wp-content/uploads/2011/04/point-b-capital-logo02.png","http://www.pointbcap.com/index.html", "VC"],

["eonCapital Ventures","eonCapital Ventures invest in seed and early-stage Software as a Service (SaaS) and mobile application businesses. Like the creative entrepreneur, we saw a problem and desired a solution. Our goal is to help fill the funding gap for entrepreneurs of seed and early-stage companies. As entrepreneurs, we understood what it takes to build a company from the ground up and the challenges presented from concept through development and into the growth phase.","http://www.boulderstartups.org/wp-content/uploads/2011/04/eon-logo.png","http://www.eonbusiness.com/", "VC"],

["Flywheel Ventures","Flywheel Ventures focuses on seed-stage and early-stage companies with solutions that address key global challenges in digital services, infrastructure technology, energy technology, and water technology. Flywheel works with each entrepreneur to grow their company in a capital-efficient manner by focusing on a 'beachhead' market, often overseas, leveraging the firm’s formal Global Advisor network and informal network of worldwide experts.","http://www.boulderstartups.org/wp-content/uploads/2011/04/flywheel.gif","http://www.flywheelventures.com/index.php", "VC"],

["Foundry Group","The Foundry Group is Boulder’s most well-known venture capitalism firm, focused on making investments in early-stage information technology, Internet and software startups with a portfolio that includes companies like Zynga, Trada, SendGrid, and many more. Foundry’s current venture fund of $225m was launched in October 2010 and is managed by four managing directors who collectively have over five decades of experience in venture capital investing and over three decades of entrepreneurial experience in founding and working in senior operating roles inside technology startups.","http://www.boulderstartups.org/wp-content/uploads/2011/04/FoundryGroup.jpg","http://foundrygroup.com/", "VC"],

["Grotech Ventures","As one of the longest-established firms in the venture industry, Grotech Ventures has built a reputation for being a collaborative, long-term partner for CEOs and entrepreneurs by aligning our definition of success with that of our partners. Grotech Ventures initially invests from $500,000 to $5 million and looks to continue investing and building value throughout the growth of your enterprise. Grotech’s portfolio includes local companies such as Collective Intellect and Giveo.","http://www.boulderstartups.org/wp-content/uploads/2011/04/grotech.jpg","http://www.grotech.com/index.php", "VC"],

["High Country Venture","High Country Venture makes active investments in promising early-stage companies that have scalable, innovative technology. We tend to take an active role in our investments, and frequently work with the founding team to foster growth, transform markets and create long-term value.","http://www.boulderstartups.org/wp-content/uploads/2011/04/logo.png","http://highcountryventure.com/newsite/wordpress/", "VC"],

["Highway 12","Like the original venture firms of the 70′s and 80′s, Highway 12 is not sector focused. The firm’s founding investment thesis is that the  Intermountain West  (the fastest growing region in the country) will produce a disproportionate amount of highly successful companies over the next couple of decades. With a singular focus on providing the early rounds of investment in the most promising high-growth companies in the region, the firm does not invest all over the country or in sectors that go in and out of favor. This unique focus on the region sets Highway 12 apart from other venture capital firms employing the latest strategy du jour. The firm spends all their time and energy here in the West, making them better able to help you gather the resources you need.","http://www.boulderstartups.org/wp-content/uploads/2011/04/highway12.jpg","http://www.highway12ventures.com/", "VC"],

["Infield Capital","Infield Capital is committed to fueling the early-stage companies that are driving change in the transportation industry.  We have an emphasis on technologies aimed at rethinking the powertrain – those things between the 'key and the wheel' that will reduce our reliance on oil and our emissions of greenhouse gases.  We have a strong belief in the entrepreneur that stems from years in manufacturing and high-tech operating roles, and an investment model that uniquely couples financial capital with human capital.","http://www.boulderstartups.org/wp-content/uploads/2010/12/Infield.png","http://www.infieldcapital.com/", "VC"],

["ACCION New Mexico-Arizona-Colorado","ACCION New Mexico • Arizona • Colorado is an award-winning nonprofit organization that invests in the community’s most important asset – human potential. By increase access to business credit, making loans and providing training to help emerging and existing entrepreneurs realize their dreams, ACCION empowers people to be catalysts for positive change – one small business at a time.","http://coloradomicrofinance.org/wp-content/uploads/2011/05/ACCION-NM-AZ-CO.jpg","http://www.accionnm.org/", "MFG"],

["Colorado Enterprise Fund","The Colorado Enterprise Fund was founded in 1976 as a non-profit lending source specializing in loans up to $250,000 to support small business. Many small businesses that are not able to receive traditional bank financing can get support through CEF. By offering loans, guidance, training, and resources to small and emerging businesses, CEF is an important conduit to local community vitality and economic development in Colorado.","http://www.coloradoenterprisefund.org/templates/cef/i/pageHeaders/home_header.jpg","http://www.coloradoenterprisefund.org/", "MFG"],

["Colorado PERA Mile High Fund","Colorado PERA Mile High Fund was launched in October of 2012 to invest a portion of it’s $40 billion fund in Colorado businesses that have a nexus in Colorado and currently have the support of a financial sponsor. The PERA Mile High Fund is intended to be a pool of growth capital for Colorado businesses.","http://innovationews.com/blog/wp-content/uploads/2012/10/colorado-pera-featured1.jpg","http://www.copera.org/pera/about/latestnews.htm#ColoradoFund", "MFG"],

["Rocky Mountain MicroFinance Institute (RMMFI)","The Rocky Mountain MicroFinance Institute (RMMFI) is a non-profit organization that provides learning, lending, and coaching to grow Community Entrepreneurs who build businesses to advance along the pathway to self-sufficiency and self-worth. RMMFI’s brand of microfinance combines affordable and approachable business support services and flexible microloans to help individuals turn a good idea into an income-generating business.","http://www.boulderstartups.org/wp-content/uploads/2011/04/rmmfi.jpg","http://www.rmmfi.org/", "MFG"],

["CU Deming Center Venture Fund","The Deming Center Venture Fund provides both capital and resource support for emerging companies in Boulder and surrounding communities. The DCVF focuses on early stage investments, providing financial support that early-stage companies often require to develop and test new products and technologies.","http://cudcvf.org/wp-content/uploads/2012/08/image_1_main.png","cudcvf.org", "AMS"],

["Fraser McCombs Capital","Fraser McCombs Capital is a venture firm focused on early-stage technology companies within the automotive space. We are the first and only venture fund that’s managed by automotive entrepreneurs and dealers. We have long standing relationships with Tier 1, 2, and 3 vendors, and connections with leading OEM executives and principals of the largest dealer groups. This allows us to provide key introductions for our portfolio companies.","http://mccombspartners.com/wp-content/uploads/2011/12/FMC_500x182.jpg","fmcap.com", "AMS"],

["Galvanize","Physical proximity to other doers, makers and innovators is important. There is no manual for entrepreneurial success. It’s a journey. A journey that is only limited on your ability to learn and grow. This type of learning comes from doing—from experience. The skills, connections, and mentorship your journey requires are coalesced here.","http://startupphenomenon.com/2013/wp-content/uploads/2013/06/galvanize-2.jpeg","galvanize.it", "AMS"],

["The Impact Angel Group","The Impact Angel Group is a network of angel investors equally dedicated to making a difference and realizing a return. The group applies best-of-breed practices to social impact investing and connects viable social entrepreneurs with financial, intellectual and human capital. The mission is to create social impact success stories for both entrepreneurs and investors. The group is a source of capital that exists to support the existing ecosystem and connect entrepreneurs and investors to the resources they need to succeed.","http://50.87.144.189/~tiag/wp-content/uploads/2013/07/cropped-cropped-istock_000018764690large1.jpg","http://impactangelgroup.com/", "AMS"],

["John Ives Tahoma Fund","John has been an early-stage investor and entrepreneur since 1997. He is co-founder of Chips on the Deck, a networking organization for Colorado-based semiconductor, EDA and embedded system entrepreneurs. He is also the founder of Boulder Angels, which organizes the activities of active, professional angel investors in Boulder County.","http://www.johnives.com/wp-content/uploads/2013/06/iveslogo3.png","http://www.johnives.com/", "AMS"],

["Open Angel Forum (OAF)","The Open Angel Forum (OAF) is dedicated to providing entrepreneurs with access to the angel investor community based solely on merit (and without fees). Additionally, we strive to build collaboration between angel investors and to inspire high-net worth individuals to become angels. Leading the Boulder chapter are none other than Brad Feld and David Cohen.","http://www.boulderstartups.org/wp-content/uploads/2011/04/openangelforum.jpg", 'N/A', "AMS"],

["Rockies Venture Club","For over 28 years, Colorado has looked to the Rockies Venture Club to connect investors, service providers, and entrepreneurs. Rockies Venture Club is a non-profit organization. RVC 2.0 envisioned in 2012 builds on RVC’s tradition of connecting investors and entrepreneurs and adds active angel groups, more sophisticated training and education, more events, a more diverse community and metric-driven action oriented approach to funding early stage companies.","http://www.denvergov.org/Portals/690/images/New/BizPlan%20Logos/RVCnew%20logo.JPG","rockiesventureclub.org", "AMS"],

["Silicon Valley Bank Financial Group","Silicon Valley Bank Financial Group provides diversified financial services to emerging, growth and established technology companies and the life science, venture capital and premium wine markets. Through its focus on specialized markets and extensive knowledge of the people and business issues driving them, SVB Financial Group provides a level of service and partnership that measurably impacts its clients’ success.","http://www.boulderstartups.org/wp-content/uploads/2011/04/svbfg-300x42.gif","http://www.svb.com/", "AMS"],

["Square 1 Bank","Square 1 Bank specializes in providing financial services to entrepreneurs and venture capitalists. We help growing companies and their investors navigate financial obstacles by providing access to funds and expertise. Our customized product offerings and unrivaled team of venture banking specialists provide a banking experience designed exclusively for you. As entrepreneurs, we have experienced what it takes to make a dream reality. We know the doubts. We know the late nights. We know the celebrations. We know that for an idea that’s never been done, flexibility is required. The unknown represents possibility not fear. We get it. We are entrepreneurs serving entrepreneurs.","http://www.boulderstartups.org/wp-content/uploads/2011/04/square1.jpg","https://www.square1financial.com/bankhome", "AMS"],


]

class_list.each do |name, code, description, discipline |
  Course.create( name: name, code: code, description: description, discipline: discipline )
end

student_groups.each do |name, description, photo, website |
	StudentGroups.create(name: name, description: description, photo: photo, website: website)
end

funding.each do |name, description, photo, website, funding_type|
	Funding.create(name: name, description: description, photo: photo, website: website, funding_type: funding_type)
end




